version: "3.7"

services:
  # image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    container_name: app
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel
  
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nginx-appboxe
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    container_name: db-apiboxe
    environment:
      POSTGRES_DB: boxeapp
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    # volumes:
    #   - ./.docker/mysql/dbdata:/var/lib/mysql
    networks:
      - laravel

  # queue
  # queue:
  #   image: especializati/laravel9-app
  #   restart: unless-stopped
  #   command: "php artisan queue:work"
  #   container_name: queue-appboxe
  #   volumes:
  #     - ./:/var/www
  #   depends_on:
  #     - redis
  #     - app
  #   networks:
  #     - laravel

  # redis
  redis:
    image: redis:latest
    container_name: redis-appboxe
    networks:
      - laravel

networks:
  laravel:
    driver: bridge